import { SliceZone } from "@prismicio/react";
import { notFound } from "next/navigation";
import { createClient } from "@/prismicio";
import { components } from "@/slices";

// Home page — content fetched from Prismic and rendered via SliceZone.
// The `homepage` singleton document is edited in the Prismic dashboard;
// this component just renders whichever slices the editor picks.
export default async function HomePage() {
  const client = createClient();

  // `getSingle` is Prismic's helper for "single-instance" types like a homepage.
  // If the doc doesn't exist yet (empty repo), fall back to a 404.
  const page = await client.getSingle("homepage").catch(() => null);
  if (!page) notFound();

  // SliceZone maps each slice on the doc to the matching React component
  // from `slices/index.ts` (generated by `prismic push`).
  return <SliceZone slices={page.data.slices} components={components} />;
}
